Added help to devlab script.

diff --git a/scripts/devlab b/scripts/devlab
--- a/scripts/devlab
+++ b/scripts/devlab
@@ -26,7 +26,6 @@
 ###################################################
 
 usage() {
-echo -e "\033[0;31mInvalid command. Usage:\033[0m"
 cat << EOF 
 devlab [-l <lang>] [-v <version>] <command>
 
@@ -43,7 +42,6 @@ stop - Stops the started jupyter (lab or notebook)
 
 If no command is given, default is "lab".
 EOF
-    exit 1
 }
 
 # First, collect all options
@@ -151,6 +149,10 @@ printjpyinfo() {
 
 # Depending on what we want to start, set up docker parameters
 case $progarg in
+"help")
+    usage
+    exit 0
+    ;;
 "shell")
     rundevlab "/bin/zsh" "-it" 
     ;;
@@ -170,5 +172,8 @@ case $progarg in
     rundevlab "starttmux" "-it"
     ;;
 *)
-    usage;;
+    echo -e "\033[0;31mInvalid command. Usage:\033[0m"
+    usage
+    exit 1
+    ;;
 esac
